mysite/book/urls.py
from django.urls import path , re_path , register_converter
from .import views



#convert برای تاریخ آرشیو
class TwoDigitDayConverter:
    regex = '[0-9]{2}'
    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return '%02d' % value





register_converter(TwoDigitDayConverter,'dd')

app_name = 'book'
urlpatterns = [
    path('', views.index , name = 'index'),
    path('list/', views.BookListView.as_view() , name = 'bookList'),
    path('mybooks/', views.LoanedBookByUserListView.as_view() , name = 'mybooks'),
    path('detail/<uuid:pk>/renew/',views.renew_book_librarian, name = 'renewBooklibrarian'),
    path('borrows/',views.BookBorrowListView.as_view(), name = 'allBorrowed'),
    # path('detail/<int:pk>/', views.BookDetailView.as_view() , name = 'bookDetail')
    re_path(r'^detail/(?P<pk>\d+)/$', views.BookDetailView.as_view() , name = 'bookDetail'),
    path('archive/<dd:day>/', views.archive_day , name = 'archive'),

    # API URL
    re_path(r'^get/$', views.APIListCreateBook.as_view() , name = 'apiBookList'),
    re_path(r'^update/(?P<pk>\d+)/$', views.APIRetrieveUpdateDestroy.as_view() , name = 'apiBookUpdate'),
    re_path(r'^getdetail/(?P<pk>\d+)/$', views.BookDetail.as_view() , name = 'apiBookDetail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^api-auth/',include('rest_framework.urls',namespace='rest_framework')),
    re_path(r'^api/v1/books/',include('book.urls',namespace='apibooks')),
]

mysite/book/models.py
import uuid
from datetime import date
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
#تعریف کلاس ژانر
class Genre(models.Model):
    name = models.CharField(max_length=200 , help_text = 'enter a book genre(e.g sciense fiction , frenchpoetry etc.)')


    def __str__(self):
        return self.name


#تعریف کلاس کتاب
class Book(models.Model):
    title = models.CharField(max_length = 200,verbose_name='عنوان')
    #توضیحات کتاب
    summary = models.TextField(max_length =1000, help_text = 'enter a brif description of the book',verbose_name='توضیحات')
    isbn = models.CharField(max_length = 13, help_text = '13 character <a href="http://www.isbn-international.org/content/what-isbn">ISBN number</a>',verbose_name='isbn کد')
    #ارتباط چند به چند (هر کتاب میتواند چندژانر داشته باشدو هر ژانر میتواند برای چند کتاب باشد )
    genre = models.ManyToManyField(Genre, help_text = 'select a genrefor this book',verbose_name='ژانر')
    #ارتباط یک به چند (هر نویسنده میتواند چند کتاب داشته باشند)
    author = models.ForeignKey('Author', on_delete =models.SET_NULL , null = True,verbose_name='نویسنده')


    class Meta:
        verbose_name = 'کتاب'
        verbose_name_plural = 'کتاب ها'
    
    def __str__(self):
        return self.title

    def get_absolute_url():
        return 


#تعریف کلاس نویسنده
class Author(models.Model):
    first_name = models.CharField(max_length =100)
    last_name = models.CharField(max_length = 100)
    date_of_birth = models.DateField(null = True, blank = True)
    date_of_death = models.DateField(null = True, blank = True)


    class Meta:
        ordering = ['last_name', 'first_name']


    def __str__(self):
        return '{0},{1}'.format(self.last_name,self.first_name)


#تعریف کلاس کپی های کتاب       
class BookInstance(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid.uuid4,
                        help_text = 'unique ID for this paticular book across whole library')                
    #ارتباط یک به چند (یک کتاب میتواند چند کپی داشته باشد )
    book = models.ForeignKey('Book', on_delete = models.SET_NULL, null = True, blank = True)
    #جزییات نسخه ها
    imprint = models.CharField(max_length =200)
    #کتاب های پس داده شده
    due_back = models.DateField(null = True, blank = True)
    #کسانی  که کتاب قرض گرفته اند
    borrower = models.ForeignKey(User,on_delete = models.SET_NULL, null = True, blank = True)
    #حالت های قرض کتابها
    LOAN_STATUSE = (
        ('m','Maintenance'),   #قرض گرفته نگه دارد
        ('o','On loan'),       #قرض گرفته برمیگرداند
        ('a','Available'),     #موجود است
        ('r','Reserved')       #رزرو شده است
    )

    statuse = models.CharField(max_length = 1, choices = LOAN_STATUSE, blank = True, default = 'a',help_text = 'Book Availablity')


    class Meta:
        ordering = ['due_back']
        permissions = (
            ("can_read_private_section","VIP_User"),
            ("user_watcher","UserWatcher"),
            ("librarian","Librarian"),
        )

   
 #محاسبه تاریخ کتاب که تاریخ برگشت  گذشته است

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        else:
            return False    
    
    def __str__(self):
        return '{0},{1}'.format(self.id,self.book.title)
         

mysite/book/forms.py
from calendar import week
from django import forms
import datetime

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


#فرم تمدیدتاریخ کتاب

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a data between now and four weeks.")



#  (validation) اعتبار سنجی
def clean_renewal_date(self):
    data = self.cleaned_data['renewal_date']
    if data < datetime.date.today():
        raise ValidationError(_('Invalid date - renewal in past'))

    if data > datetime.date.today() + datetime.timedelta(weeks = 4):
        raise ValidationError(_('Invalid date - renewal more than 4 wreeks ahead.'))

    return data

mysite/book/views.py
import datetime 
#from datetime import datetime
from msilib.schema import ListView
from multiprocessing import context



from django.shortcuts import get_object_or_404, render
from django.views import generic


from django.http import HttpResponseRedirect
from django.urls import reverse



 # as a function
from django.contrib.auth.decorators import login_required             #  برای محدودیت به روش دکوریتور
from django.contrib.auth.decorators import permission_required        # برای محدودیت به پرمیشن 
from django.contrib.auth.decorators import user_passes_test           # محدودیت سفارشی

from .serializer import BookSerializer
from .serializer import BookDetailSerializer
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import api_view



#as a generic
from django.contrib.auth.mixins import LoginRequiredMixin             #  برای محدودیت به روش دکوریتور
from django.contrib.auth.mixins import PermissionRequiredMixin            # برای محدودیت به پرمیشن 
from django.contrib.auth.mixins import UserPassesTestMixin             # محدودیت سفارشی 

from .forms import RenewBookForm           


from .models import Author
from .models import Book
from .models import BookInstance
from .models import Genre
from .forms import RenewBookForm


# Create your views 



#@login_required                         #لاگین چک میشود
#@permission_required('book.can_read_private_section')    # پرمیشن چک میشود
#@permission_required('book.user_watcher')  
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(statuse__exact = 'a').count()
    num_author = Author.objects.all().count()
    context ={
        'num_books' : num_books,
        'num_instances' : num_instances,
        'num_instances_available' : num_instances_available,
        'num_author': num_author,

    
    }
     
    return render(request, 'book/index.html',context)

#کتاب های قرض گرفته شده

class BookBorrowListView(LoginRequiredMixin ,PermissionRequiredMixin ,generic.ListView):
    model = BookInstance
    paginate_by = 2
    permission_required = "book.librarian"
    template_name ="book/book_borrows.html"

    def get_queryset(self):
        return BookInstance.objects.filter(statuse__exact = 'o')


# لیست کتاب ها
class BookListView(LoginRequiredMixin,PermissionRequiredMixin , generic.ListView):   #لاگین چک میشود بعد پرمیشن
    model = Book
    paginate_by = 2
    permission_required = "book.can_read_private_section"
    permission_required = "book.user_watcher"


    



   #است django آنهاشامل title کتاب هایی که
    #
    #def get_queryset(self):
    #    return Book.objects.filter(title__icontains = 'django')

   
    #def get_context_data(self, **kwargs):
    #    context = super(BookListView, self).get_context_data(**kwargs) 
    #    context['my_book_list'] = Book.objects.all()
    #    return context


class BookDetailView(generic.DetailView):
    model = Book





class LoanedBookByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'book/bookinstance_list_borrower_user.html.'
    paginate_by = 3

    def get_queryset(self):
        return BookInstance.objects.filter(borrower = self.request.user).filter(statuse__exact = 'o').order_by('due_back')



#تمدید تاریخ

@login_required
@permission_required('book.librarian')
def renew_book_librarian(request,pk):
    book_inst = get_object_or_404(BookInstance, pk = pk) 

    if request.method == 'POST':
        form = RenewBookForm(request.POST)
        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()
            return HttpResponseRedirect(reverse('book:allBorrowed'))
    else:
        proposed_renewal_data = datetime.date.today() + datetime.timedelta(weeks = 3)
        form = RenewBookForm(initial={'renewal_date':proposed_renewal_data})

    context = {
        'form': form,
        'book_inst': book_inst
        } 
        

    return render(request,
     'book/book_renew_librarian.html',
      context
      )


      
#تابع آرشیو روز بازگشت کتابها
def archive_day(request , day):
    day_archive_books = BookInstance.objects.filter(due_back__day = day)
    context={
        "day_archive_books" : day_archive_books,
    }
    return render(request, 'book/archive.html', context )




#API

class APIListCreateBook(generics.ListCreateAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    #permission_classes = [IsAuthenticated]                #post,get
    permission_classes = [IsAuthenticatedOrReadOnly]     # only get

 
class APIRetrieveUpdateDestroy(generics.RetrieveUpdateDestroyAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    #permission_classes = [IsAuthenticated]                #post,get
    permission_classes = [IsAuthenticatedOrReadOnly]     # only get

#@api_view(["GET"])
#def book_Detail(request,pk):
#    book = Book.objects.get(pk = pk)
#    book_serialize  = BookDetailSerializer(book)
#    return Response(book_serialize.data)

class BookDetail(generics.ListCreateAPIView):
    queryset =BookInstance.objects.all()
    serializer_class = BookDetailSerializer


    

mysite/media/templates/book/archive.html
{% extends 'shared/site.html' %}
{% block body %}
    <div class = "container">
        <div style="margin-top: 50px;"></div>
        <h1 class="text-center">
            All book
        </h1>
    </div>
    {% if day_archive_books %}
        <div class = "table-responsive">
            <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">book</th>
                    <th scope="col">borrower</th>
                    
                  </tr>
                </thead>
                <tbody>
                    {% for bookinst in day_archive_books %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{bookinst.book}}</td>
                            <td>{{bookinst.borrower}}</td>
                            
                        </tr>    
                    {% endfor %}     
                </tbody>
            </table>  
        </div> 

        
    {% else %} 
        <h1>No books are found!!!</h1>
    {% endif %}

    {% include 'partials/pagination.html' %}
    {% include 'partials/navigation.html' %}
       

    
{% endblock %}

mysite/media/templates/book/book_borrows.html
{% extends 'shared/site.html' %}
{% block body %}
    <div class = "container">
        <div style="margin-top: 50px;"></div>
        <h1 class="text-center">
            All borrower
        </h1>
    {% if bookinstance_list %}
        <div class = "table-responsive">
            <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Due_Back</th>
                    <th scope="col">User</th>
                  </tr>
                </thead>
                <tbody>
                    {% for bookinst in bookinstance_list %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{bookinst.book}}</td>
                            <td>{{bookinst.due_back}}</td>
                            <td>{{bookinst.borrower}}</a>
                        </tr>
               
                    {% endfor %}
                    {% endif %}           
                </tbody>
            </table>  
        </div>   
    </div>     
        {% include 'partials/pagination.html' %}
        {% include 'partials/navigation.html' %}

{% endblock %}        

mysite/media/templates/book/book_detail.html
{% extends 'shared/site.html' %}
{% block body %}
    <p>{{book.title}}</p>
    <p>{{book.summary}}</p>
    <p>{{book.isbn}}</p>

    {% for copy in book.bookinstance_set.all %}
        {% if copy.statuse == 'o' %}
           <p>{{copy.due_back}}</p> 
           <p>{{copy.imprint}}</p>
           <p>{{copy.id}}</p>
        {% endif %}
    {% endfor %}       
{% endblock %}

mysite/media/templates/book/book_list.html
{% extends 'shared/site.html' %}
{% block body %}
    <div class = "container">
        <div style="margin-top: 50px;"></div>
        <h1 class="text-center">
            All books
        </h1>
       

    </div>
    {% if book_list %}
        <div class = "table-responsive">
            <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">ISBN</th>
                    <th scope="col">Detail</th>
                  </tr>
                </thead>
                <tbody>
                    {% for book in book_list %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{book.title}}</td>
                            <td>{{book.isbn}}</td>
                            <td><a class = "btn btn-info btn-block" href="{% url 'book:bookDetail' book.id %}">info</a></td>
                        </tr>    
                    {% endfor %}     
                </tbody>
            </table>  
        </div>    

    
    {% else %}   
        <h1>No book are found!!!</h1>
    {% endif %}
    
    {% include 'partials/pagination.html' %}
    {% include 'partials/navigation.html' %}
    
{% endblock %}

mysite/media/templates/book/book_renew_librarian.html
{% extends 'shared/site.html' %}
{% block body %}
<div class = "container">
    <div style="margin-top: 50px;"></div>
    <h1 class="text-center">
        All books
    </h1>
    <div style="margin-bottom: 100px;"></div>
    {% if form.errors %}
        {% for error,message in form.errors.items %}
          <div class="alert alert-danger">{{ error }} {{ message }}</div>
        {% endfor %}
    {% endif %}
    <h1>Renew: {{ book_inst.book.title }}</h1>
    <p>borrower: {{ book_inst.borrower }}</p>
    <p {% if book_inst.is_overdue %} class="text-danger" {% endif %}>Due date:{{book_inst.due_back}}</p>

        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="renewal_date">{{form.renewal_date.label}}:</label>
                {{form.renewal_date}}
              
            </div>
            <input  class="btn btn-info" type="submit" value="submit">
        </form> 
</div>
        
  {% include 'partials/pagination.html' %}
  {% include 'partials/navigation.html' %}

{% endblock %}   

mysite/media/templates/book/bookinstance_list_borrower_user.html
{% extends 'shared/site.html' %}
{% block body %}
<div class = "container">
    <div style="margin-top: 50px;"></div>
    <div style="margin-bottom: 100px;"></div>
    <section class="borrowed">
        <h1 class="text-center text-dark">Borrowed books</h1>
        {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class= "{% if bookinst.is_overdue %}text-danger{% else %}text-dark {% endif %}">
                    <a class = "logout-link" href="{% url 'book:bookDetail' bookinst.book.pk %}">{{bookinst.book.title}}</a><span>({{bookinst.due_back}})</span>
                </li>
            {% endfor %}
        </ul>
        {% else %}
            <p class="text-center text-dark">There are no books borrowed.</p>
        {% endif %}
    </section>
</div>

<div style="margin-top: 50px;"></div>
    <div style="margin-bottom: 100px;"></div>
    <section class="borrowed">
        <h1>private section</h1>
        {% if perms.book.can_read_private_section %}
            <p>Here is important description to<strong>VIP</strong>Users</p>

            {% if perms.book.user_watcher %}
                <small>Enterd username is:<strong style="text-transform:capitalize;"class="logout-link">{{user}}</strong></small>
            {% else %}
                <small style="color: tomato;">You don't have permission to see here.</small>
            {% endif %}
        {% else %}  
          <p style="color: tomato;">You don't have permission to see here.></p>
        {% endif %}
        
    </section>
</div>

{% include 'partials/navigation.html' %}

{% endblock %}    

mysite/media/templates/book/index.html
{% extends 'shared/site.html' %}
{% block body %}
<div class = "container-fluid">
   <br/>
   <br/>
   <br/>


   <p>number of books : {{num_books}}</p> 
   <p>number of instances : {{num_instances}}</p>
   <p>number of instances_available : {{num_instances_available}}</p>
   <p>number of author : {{num_author}}</p> 
</div>  


{% include 'partials/navigation.html' %}


{% endblock %}