mysite/book/urls.py
from django.urls import path , re_path , register_converter
from .import views



#convert برای تاریخ آرشیو
class TwoDigitDayConverter:
    regex = '[0-9]{2}'
    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return '%02d' % value





register_converter(TwoDigitDayConverter,'dd')

app_name = 'book'
urlpatterns = [
    path('', views.index , name = 'index'),
    path('list/', views.BookListView.as_view() , name = 'bookList'),
    path('mybooks/', views.LoanedBookByUserListView.as_view() , name = 'mybooks'),
    path('detail/<uuid:pk>/renew/',views.renew_book_librarian, name = 'renewBooklibrarian'),
    path('borrows/',views.BookBorrowListView.as_view(), name = 'allBorrowed'),
    # path('detail/<int:pk>/', views.BookDetailView.as_view() , name = 'bookDetail')
    re_path(r'^detail/(?P<pk>\d+)/$', views.BookDetailView.as_view() , name = 'bookDetail'),
    path('archive/<dd:day>/', views.archive_day , name = 'archive'),

    # API URL
    re_path(r'^get/$', views.APIListCreateBook.as_view() , name = 'apiBookList'),
    re_path(r'^update/(?P<pk>\d+)/$', views.APIRetrieveUpdateDestroy.as_view() , name = 'apiBookUpdate'),
    re_path(r'^getdetail/(?P<pk>\d+)/$', views.BookDetail.as_view() , name = 'apiBookDetail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^api-auth/',include('rest_framework.urls',namespace='rest_framework')),
    re_path(r'^api/v1/books/',include('book.urls',namespace='apibooks')),
]

mysite/media/templates/partials/navigation.html
<nav class="navbar navbar-expand-lg bg-dark fixed-top ">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Local library</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'book:index' %}">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              section
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'book:bookList' %}">All books</a></li>
              <li><a class="dropdown-item" href="#">All authors</a></li>
             
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
             librarian
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'book:allBorrowed' %}">All borrowed</a></li>
            </ul>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
       
      </div>
      {% if user.is_authenticated %}  
          <a href ="{% url 'logout' %}"><button class="btn btn-outline-info" style = "margin-right:8px;">Sign Out</button></a>
      {% else %}    
          <a href ="{% url 'login' %}"><button class="btn btn-info" style = "margin-right:8px;">Sign In</button></a>
          <a href ="#"><button class="btn btn-outline-info">Sign Up</button></a>
      {% endif %}

       
    </div>
  </nav>

mysite/media/templates/partials/pagination.html
{% if is_paginated %}   
    <nav aria-label="page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href = "{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                </li>
            {% else %}   
                <li class="page-item disabled">
                    <a class="page-link" href="#">previous</a>
                </li> 
            {% endif %}

            {% for i in paginator.page_range %} 
                {% if page_obj.number == i %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">{{ i }}</a>
                    </li>
                {% else %}   
                    <li class="page-item">
                        <a class="page-link" href="{{ request.path }}?page={{ i }}">{{ i }}</a>
                    </li> 
                {% endif %} 
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href = "{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                </li>
            {% else %}   
                <li class="page-item disabled">
                    <a class="page-link" href="#">next</a>
                </li>     
            {% endif %}  
        </ul>
    </nav>      
    {% endif %}   
    